name: LAPIG
channels:
- defaults
- nvidia
- pytorch
- conda-forge
dependencies:
- python=3.10.4
- pip=24.0
- pytorch-cuda=12.1
- brotli-python=1.0.9
- pysocks=1.7.1
- cudnn=8.1.0.77
- pip:
  - pyparsing==3.1.2
  - opencv-python==3.4.18.65
  - accelerate==0.32.1
  - diffusers==0.29.2
  - omegaconf==2.3.0
  - tifffile==2024.7.2
  - tensorflow==2.10.1
  - visdom==0.2.4
  - torchvision==0.18.1
  - python-dateutil==2.9.0.post0
  - opencv-contrib-python==4.9.0.80
  - pyqt5==5.15.10
  - pandas==2.2.2
  - scikit-image==0.24.0
  - scipy==1.14.0
  - matplotlib==3.9.1
  - torchaudio==2.3.1
  - watchdog==4.0.1
  - imageio==2.34.2
  - transformers==4.42.4
  - opencv-python-headless==4.10.0.84
